# https://github.com/hankcs/HanLP
# https://github.com/medcl/elasticsearch-analysis-pinyin
# https://github.com/KennFalcon/elasticsearch-analysis-hanlp
# https://github.com/medcl/elasticsearch-analysis-ik

FROM elasticsearch:7.8.0
ARG plugin_version=7.8.0
RUN set eux \
  ; elasticsearch-plugin install --batch \
    https://github.com/medcl/elasticsearch-analysis-pinyin/releases/download/v${plugin_version}/elasticsearch-analysis-pinyin-${plugin_version}.zip \
  ; elasticsearch-plugin install --batch \
    https://github.com/medcl/elasticsearch-analysis-ik/releases/download/v${plugin_version}/elasticsearch-analysis-ik-${plugin_version}.zip \
  ; chown -R 1000 plugins \
  ; sed -e 's!\(remote_ext_stopwords">\).*\(</entry>\)!\1'"http://localhost/txt/stopwords"'\2!' \
        -e 's!\(remote_ext_dict">\).*\(</entry>\)!\1'"http://localhost/txt/dict"'\2!' \
        /usr/share/elasticsearch/config/analysis-ik/IKAnalyzer.cfg.xml
